snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "(row1 OBJECT)"
return_type = "STRING"
file = "app.zip"
name = "get_active_behaviors"
handler = "app.get_active_behaviors"
execute_as_caller = true

[dev]
database = "CONSUMER_INFO"
schema = "CONSUMER_INFO"
warehouse = "TEAM2_DW"
role = "TEAM2_ROLE"
overwrite = true